version: '2'
services:
    cws-app:
        image: cws
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cws-mysql:3306/cws?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cws-mysql:
        extends:
            file: mysql.yml
            service: cws-mysql
